### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by copolii** [bonnyfone/vectalign#6]
java -jar vectalign-0.2-jar-with-dependencies.jar --start "M 16 17 A 1,1,0,1,0,15,16 A 1,1,0,0,0,16,17 Z M 16 18 A 2,2,0,1,1,18,16 A 1.9994,1.9994,0,0,1,16,18 Z M 16.95 15.948 L 16.4 15.948 L 16.4 15.125 L 15.577 15.125 L 15.577 15.948 L 15.028 15.948 L 15.988 16.91 Z" --end "M16,26C21.52,26 26,21.52 26,16C26,10.48 21.52,6 16,6C10.48,6 6,10.48 6,16C6,21.52 10.48,26 16,26ZM16,28C9.37,28 4,22.63 4,16C4,9.37 9.37,4 16,4C22.63,4 28,9.37 28,16C28,22.63 22.63,28 16,28ZM21.7,15.69L18.4,15.69L18.4,10.75L13.46,10.75L13.46,15.69L10.17,15.69L15.93,21.46L21.7,15.69Z" --mode BASE

Sequences sizes: 16 / 21
Aligning mode: BASE
0. align iteration...
Alignment found!
M A A # # # # L M A A # # # # L M # L L L L L L L
M # # C C C C L M # # C C C C L M L L L L L L L L
Sequence aligned! (25 elements)
###################### EXCEPTION #####################
java.lang.ArrayIndexOutOfBoundsException: 7
        at com.bonnyfone.vectalign.techniques.BaseFillMode.fillInjectedNodes(BaseFillMode.java:93)
        at com.bonnyfone.vectalign.VectAlign.align(VectAlign.java:120)
        at com.bonnyfone.vectalign.Main.main(Main.java:104)
######################################################

**Comment by enzet** [comment]
Minimized arguments: `--start "M 16 17 A 1,1,0,1,0,15,16 Z" --end "M 16,26 Z"`.

Output:

```
Sequences sizes: 3 / 2
Aligning mode: BASE
0. align iteration...
Alignment found!
M A L 
M # L 
Sequence aligned! (3 elements)
###################### EXCEPTION #####################
java.lang.ArrayIndexOutOfBoundsException: 7
	at com.bonnyfone.vectalign.techniques.BaseFillMode.fillInjectedNodes(BaseFillMode.java:93)
	at com.bonnyfone.vectalign.VectAlign.align(VectAlign.java:120)
	at com.bonnyfone.vectalign.Main.main(Main.java:104)
######################################################
```
